-
  name: CATAPP
  dir: /home/vmaryn/projects/go/cli
  cmd: docker run --rm -p=27017:27017 mongo
-
  name: DOCKAPP
  dir: /home/vmaryn/projects/go/sandbox
  cmd: docker-compose up
-
  name: DOCKAPP2
  dir: /home/vmaryn/projects/go/sandbox
  cmd: docker-compose up